version: '3.8'

services:
  postgres:
    image: postgres:15.2-alpine
    container_name: pointi-postgres
    env_file:
      - pointi.env
    ports:
      - "5433:5432"
    volumes:
      - pgdata:/var/lib/postgresql/data
    networks:
      pointi-network:
        ipv4_address: 172.18.236.10
    restart: always

  pgadmin:
    image: dpage/pgadmin4:latest
    container_name: pgadmin
    env_file:
      - pointi.env
    ports:
      - "8080:80"
    depends_on:
      - postgres
    networks:
      pointi-network:
        ipv4_address: 172.18.236.11
    restart: always

  backend:
    build: ./backend
    container_name: backend
    env_file:
      - pointi.env
    ports:
      - "5000:5000"
    depends_on:
      - postgres
    networks:
      pointi-network:
        ipv4_address: 172.18.236.12
    restart: always

  nginx:
    image: nginx:alpine
    container_name: pointi-nginx
    ports:
      - "80:80"
    volumes:
      - ./nginx/nginx.conf:/etc/nginx/nginx.conf
    depends_on:
      - backend
      - pgadmin
    networks:
      pointi-network:
        ipv4_address: 172.18.236.13
    restart: always

volumes:
  pgdata:

networks:
  pointi-network:
    name: pointi-network
    driver: bridge
    ipam:
      driver: default
      config:
        - subnet: 172.18.236.0/24
