apiVersion: 1

datasources:
  - name: PostgreSQL
    type: postgres
    access: direct  # Use direct connection to the database (not proxy)
    url: "pointi-postgres:5432"  # Direct connection URL (no http://)
    user: ${POSTGRES_USER}
    database: ${POSTGRES_DB}
    secureJsonData:
      password: ${POSTGRES_PASSWORD}
    jsonData:
      sslmode: "disable"  # Disable SSL (enable if necessary)